---
from:
- "PHB"
paths:
  compendium: "/compendium/"
  rules: "/compendium/rules/"
include:
- "race|changeling|mpmm"
includeGroup:
- "familiars"
exclude:
- "monster|expert|dc"
- "monster|expert|sdw"
- "monster|expert|slw"
excludePattern:
- "race|.*|dmg"
template:
  background: "examples/templates/tools5e/images-background2md.txt"
useDiceRoller: true
tagPrefix: "ttrpg-cli"
images:
  internalRoot: "local/path/for/remote/images"
  copyInternal: true
  copyExternal: true
full-source:
  adventure:
  - "LMoP"
  book:
  - "PHB"
  homebrew:
  - "homebrew/collection/Kobold Press; Deep Magic 14 Elemental Magic.json"
