---
from:
- "PHB"
paths:
  compendium: "/compendium/"
  rules: "/compendium/rules/"
include:
- "race|changeling|mpmm"
includeGroup:
- "familiars"
exclude:
- "monster|expert|dc"
- "monster|expert|sdw"
- "monster|expert|slw"
excludePattern:
- "race|.*|dmg"
template:
  background: "examples/templates/tools5e/images-background2md.txt"
full-source:
  book:
  - "PHB"
  adventure:
  - "LMoP"
