---
from:
- "CRB"
- "GMG"
paths:
  compendium: "compendium/"
  rules: "compendium/rules/"
include:
- "ability|buck|b1"
exclude:
- "background|insurgent|apg"
excludePattern:
- "background|.*|lowg"
template:
  ability: "../path/to/ability2md.txt"
full-source:
  book:
  - "crb"
  - "gmg"
